apiVersion: v1
kind: Service
metadata:
  name: react-helloworld
spec:
  selector:
    app: react-helloworld
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer        

---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-helloworld
  template:
    metadata:
      labels:
        app: react-helloworld
    spec:
      containers:
      - image: rakeshpriyad/react-helloworld:1.0
        name: container1
        imagePullPolicy: IfNotPresent

